import './globals.css'
import {Inter} from 'next/font/google'
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import {ThemeProvider} from "@/context/ThemeContext";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Next App',
    description: 'Generated by create next app',
}



export default function RootLayout({children}) {
    return (
        <html lang="en">

        <head></head>
        {/*<link rel="preconnect" href="https://fonts.googleapis.com"/>*/}
        {/*<link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin/>*/}


        {/*<body className={inter.className}>*/}

        <ThemeProvider>
            <div className="wrapper">

                <Header/>
                <div>

                    <div className="container">
                        {children}
                    </div>

                </div>
                <Footer/>
            </div>
        </ThemeProvider>

        {/*</body>*/}
        </html>
    )
}
