import './globals.css'
import {Inter} from 'next/font/google'
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import {ThemeProvider} from "@/context/ThemeContext";
import AuthProvider from "@/components/AuthProvider/AuthProvider";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        {/*<body className={inter.className}>*/}

        <ThemeProvider>
            <AuthProvider>
                <div className="wrapper">

                    <Header/>
                    <div>

                        <div className="container">
                            {children}
                        </div>

                    </div>
                </div>
                <div className="footer">
                    <Footer/>
                </div>
            </AuthProvider>
        </ThemeProvider>

        {/*</body>*/}
        </html>
    )
}
